Platforms: Cloud Images ~ ppc64el 번역 작업
ubuntu-kr/blog.ubuntu-kr.org pull request #28
Opened 2022-04-28 04:53 UTC by onting

Close #10 
Platforms 부분의 번역입니다.

2022-04-29 16:44 UTC, sukso96100 requested changes
수고하셨습니다 :) 코멘트를 참고하여 조금 더 개선해 주시면 감사하겠습니다.

2022-04-29 16:44 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +22.04 LTS에서 부터, 이제 IBM POWER (ppc64el)를 위한 우분투 서버 이미지는 Power9 프로세서에 맞춰서 '--with-cpu=power9'을 사용해서 컴파일 됩니다 ([bug 1930086](https://bugs.launchpad.net/bugs/1930086)).
```suggestion
22.04 LTS부터, 이제 IBM POWER (ppc64el)를 위한 우분투 서버 이미지는 Power9 프로세서에 맞춰서 '--with-cpu=power9'을 사용해서 컴파일 됩니다 ([bug 1930086](https://bugs.launchpad.net/bugs/1930086)).
```

2022-04-29 16:44 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +우분투 서버 20.04 LTS는 여전히 Power8 시스템에서 몇년동안은 사용 될수는 있습니다 - 최소한 기본 지원의 끝인 2025년 4월까지는 말입니다. Power8에서 우분투 서버를 돌리고 있는 사용자는 'do-release-upgrade'를 이용해서 22.04 LTS 업그레이드 하는 방법이 끊기게 되고, 고로 이는 몇몇 시스템을 고장낼 것이 분명합니
"이러한 시스템을 망가트릴 것이기 때문에 'do-release-upgrade' 로 업그레이드 되는것이 막힐 것이다" 라는 맥락으로 옮기는게 맞는 것 같내요.

2022-04-29 23:02 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +우분투 서버 20.04 LTS는 여전히 Power8 시스템에서 몇년동안은 사용 될수는 있습니다 - 최소한 기본 지원의 끝인 2025년 4월까지는 말입니다. Power8에서 우분투 서버를 돌리고 있는 사용자는 'do-release-upgrade'를 이용해서 22.04 LTS 업그레이드 하는 방법이 끊기게 되고, 고로 이는 몇몇 시스템을 고장낼 것이 분명합니
맞네요 그 맥락이 적절한 것 같아요

2022-04-29 23:02 UTC, onting commented
> 수고하셨습니다 :) 코멘트를 참고하여 조금 더 개선해 주시면 감사하겠습니다.

꼼꼼히 봐주셔서 감사합니다:)

2022-05-01 05:45 UTC, sukso96100 requested changes

2022-05-01 05:45 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +우분투 서버 20.04 LTS는 여전히 Power8 시스템에서 몇년동안은 사용 될 수는 있습니다 - 최소한 기본 지원의 끝인 2025년 4월까지는 말입니다. Power8에서 우분투 서버를 돌리고 있는 사용자는 'do-release-upgrade'를 이용해서 22.04 LTS 업그레이드 하는 방법이 끊기게 되고, 이는 이런 시스템들을 망가뜨릴 것이 분명하기
```suggestion
우분투 서버 20.04 LTS를 여전히 Power8 시스템에서 몇년간 사용 할 수는 있습니다 - 최소한 기본 지원의 끝인 2025년 4월까지는 말입니다. Power8에서 우분투 서버를 돌리고 있는 사용자는 'do-release-upgrade'로 22.04 LTS 업그레이드 할 수 없게 되는데, 해당 방법이 시스템을 망가뜨리기 때문입니다 ([bug 1960255](https://bugs.launchpad.net/bugs/1960255)).

```

2022-05-01 06:47 UTC, sukso96100 approved these changes
수고하셨습니다. :)

2022-05-01 06:47 UTC, merged