Ubuntu Sever Main Promotion ~ Ceph 구간 번역 #20
ubuntu-kr/blog.ubuntu-kr.org pull request #31
Opened 2022-04-30 11:06 UTC by ujuc

- Ubuntu Server Main Promotion
- LXD 5.0 LTS
- Ceph

#20

2022-04-30 16:24 UTC, sukso96100 requested changes
번역을 제출 해 주셔서 감사합니다 :) 리뷰 커멘트를 참고하셔서 조금 더 개선 해 주시면 감사하겠습니다.

2022-04-30 16:24 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * [frr](https://www.frrouting.org/): 인터넷 라우팅 프로토콜 제품모음 (BGP, OSPF, IS-IS, ...)
```suggestion
 * [frr](https://www.frrouting.org/): 인터넷 라우팅 프로토콜 모음 (BGP, OSPF, IS-IS, ...)

```

`product`나 비슷한 의미의 단어가 없는 것으로 보여, `제품`이라는 단어는 빼는 것이 더 맞는 것 같습니다.

2022-04-30 16:24 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +### 우분투 서버 Main 프로모션
바로 이어 나오는 "following source packages were promoted to main" 를 "다음 소스 패키지가 메인 페키지로 승격되었습니다" 로 번역 하신 것을 보아 이쪽에 일관성을 맞추면, "우분투 서버 메인 패키지 승격", "우분투 서버 메인 승격" 등으로도 번역이 가능할 것 같습니다.

2022-05-01 06:42 UTC, sukso96100 approved these changes
이정도면 좋은 것 같습니다. 감사합니다 :)

2022-05-01 06:43 UTC, merged

2022-05-01 06:48 UTC, ujuc commented
엇.. gpg키 잘못되서 해결하고 왔더니 ㅎㅎㅎㅎㅎ 다음번꺼 번역해서 올릴께요.