Frr chrony
ubuntu-kr/blog.ubuntu-kr.org pull request #32
Opened 2022-05-01 07:55 UTC by neeks76

이렇게 하는 건지 모르겠네요.
살펴 주셔요~~

2022-05-01 08:17 UTC, sukso96100 commented
PR 대상 브랜치 변경 해 드렸습니다.

2022-05-01 08:23 UTC, sukso96100 requested changes
- 하십시오체로 모두 바꿔주시기 바랍니다. (예시: `안녕하십니까.`, `다시 한번 확인 하십시오.` `새로운 기능이 추가되었습니다.`)
- 한 문장으로 되어 있는 문장은 번역문에서도 한 문장으로 유지 해 주세요.
- 번역 팀 규정을 다시 한번 확인 하시기 바랍니다. https://wiki.ubuntu.com/UbuntuKoreanTranslators

2022-05-01 08:23 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +'quagga'는 Ubuntu 22.04에서 삭제 되었고요. FRRouting 으로 변경되었어요. ('frr', https://frrouting.org/).
```suggestion
'quagga'는 Ubuntu 22.04에서 삭제 되었으며 FRRouting 으로 대체되었습니다. ('frr', https://frrouting.org/).

```

2022-05-01 08:23 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * GnuTLS에서 AES-CMAC 해쉬 기능이 추가 지원해요.
```suggestion
 * GnuTLS에서 AES-CMAC 해쉬 기능이 지원을 추가하였습니다.

```

2022-05-01 11:06 UTC, sukso96100 commented
커멘트를 참고하셔서 추가로 수정 하신 후, 동일한 브랜치에 추가로 커밋을 올려 주시기 바랍니다. @neeks76

2022-05-02 13:50 UTC, onting commented
#32 와 중복되는 PR이기 때문에 닫겠습니다.
git push하고 나면 설정이 막혀있지 않다면 현재 진행 중인 PR에 내용이 반영되기 때문에 작업 commit을 자신의 원격 저장소에 추가하는 형식으로 하시면 됩니다. 현재 작업하신 내용이 #32 에 반영되어 있는 상태이니 그쪽에서 진행하시면 될 것 같네요 :)

2022-05-02 13:53 UTC, onting commented
실수로 잠깐 닫았습니다.

2022-05-02 15:43 UTC, sukso96100 requested changes
추가로 개선하셔야 할 부분을 커멘트 달아 드렸으니 수정해서 올려 주시기 바랍니다.

2022-05-02 15:43 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * Chrony 서비스에는 Hardening 옵션이 추가 되었습니다.
```suggestion
 * Chrony 서비스에 추가적인 하드닝(Hardening) 옵션을 추가하고 활성화 하였습니다
```
further, enabled 에 대한 번역이 누락되었습니다. 위 번역을 제안합니다.

2022-05-02 15:43 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * 설정에서 생성한 타임마스터의 시간을 읽는 기능이 허용되었습니다.
```suggestion
 * timemaster에서 생성한 구성을 읽는 것을 허용했습니다
```
- timemaster 는 고유명사로 간주하고 원문 그대로 유지해야 합니다.
  - http://manpages.ubuntu.com/manpages/xenial/man8/timemaster.8.html
- configuration 은 "구성"으로 옮겨주시기 바랍니다.
  - http://terms.tta.or.kr/dictionary/dictionaryView.do?word_seq=039507-1

2022-05-02 15:43 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * GnuTLS에서 AES-CMAC 해쉬 기능 지원을 추가하였습니다.
```suggestion
 * GnuTLS에 AES-CMAC 해시 함수 지원을 추가하였습니다

```
암호학 관련 맥락에서 hash function 은 "해시 함수"로 옮기는 것이 적절합니다.
http://terms.tta.or.kr/dictionary/dictionaryView.do?word_seq=044856-1

2022-05-02 15:43 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * 서버의 인터리브 모드가 조금 더 안정적으로 향상되었으며 NAT 뒤에 다중 클라이언트를 지원합니다.
```suggestion
 * 서버의 인터리브 모드가 조금 더 안정적으로 향상되었으며 NAT 뒤에 다중 클라이언트를 지원합니다

```

2022-05-02 15:43 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * 인터리브 모드의 Serverstats 보고에 대한 상태 기능이 추가 되었습니다.
```suggestion
 * Serverstats 보고서에 인터리브 모드에 대한 통계를 추가하였습니다

```

2022-05-02 15:43 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +Chrony는 버전 4.2로 업데이트 되었으며 다음을 포함합니다.
```suggestion
Chrony는 버전 4.2로 업데이트 되었으며 다음을 포함합니다

```

2022-05-03 13:32 UTC, merged

2022-05-03 13:33 UTC, sukso96100 commented
아 다른 부분은 번역 할당 없으시군요. 다른부분 번역 원하시면 추가로 할당 요청 하시면 됩니다.

수고하셨습니다. :)