Apache has been updated to 2.4.52 from 2.4.48 구간 번역
ubuntu-kr/blog.ubuntu-kr.org pull request #37
Opened 2022-05-04 15:33 UTC by HaeyoonJo

https://github.com/ubuntu-kr/blog.ubuntu-kr.org/issues/34 구간 번역

- 번역 구간: Apache has been updated to 2.4.52 from 2.4.48

2022-05-04 15:38 UTC, HaeyoonJo commented
@sukso96100 https://github.com/ubuntu-kr/blog.ubuntu-kr.org/issues/34 할당해주신 페이지에서 우선적으로 구간 번역을 진행하였습니다.
- HaeyoonJo-iiq는 제 로컬에서 사용된 다른 유저명으로 커밋되어버렸는데, 사용자명 수정이 필요한 경우 알려주시면 감사하겠습니다.
- 처음으로 다른 레포에 PR를 하였는데 혹시 실수하였다면 언급부탁드립니다. Reviewers를 추가해야하는 부분에서 권한이 없는 것 같아, 우선적으로 놔두었습니다.

2022-05-06 12:13 UTC, sukso96100 approved these changes

2022-05-06 12:13 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + - 개선된 hostname 그리고 UDS URI 검사 및 처리, 상태코드 응답 등을 포함한 수많은 수정사항이 있습니다.
```suggestion
 - 개선된 hostname과 UDS URI 검사 및 처리, 상태코드 응답 등을 포함한 수많은 수정사항이 있습니다.
```
검사 및 처리를 개선 했다는 것이 hostname 까지 포함하는것으로 보여서 `hostname과 UDS URI 검사 및 처리`로 옮기는 것이 조금 더 좋을 것 같습니다.

2022-05-06 12:14 UTC, sukso96100 requested changes
커멘트 참고하셔서 조금 개선 해 주시기 바랍니다. 수고하셨습니다 :)

2022-05-06 17:32 UTC, HaeyoonJo commented
꼼꼼하게 확인해주셔서 감사드립니다. 다시, PR 하였으며 확인부탁드리겠습니다!

2022-05-06 17:41 UTC, sukso96100 approved these changes
수고하셨습니다. 나머지 부분도 번역해서 제출 해주세요 :)

2022-05-06 17:42 UTC, merged