Translate PostgreSQL 14
ubuntu-kr/blog.ubuntu-kr.org pull request #38
Opened 2022-05-06 21:37 UTC by HaeyoonJo

PostgreSQL 14 파트를 번역하였습니다. 

- 번역하면서 고유명사 또는 한글로 표기하도록 하였으며, 일부 번역은 원문에 없더라도 독자의 이해를 돕기 위해 일부 추가 및 풀어서 번역을 하였습니다. 

이번 번역은 직역하기가 애매모호한 부분들이 다소 있어서 어떻게 하면 독자에게 잘 이해가 전달될까를 나름 고민해봤는데, 제가 남긴 코멘트들을 참고해주셔서 수정이 필요할지 검토부탁드리겠습니다. 
감사합니다!

2022-05-06 21:38 UTC, HaeyoonJo commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 베큠(VACUUM)은 데이터베이스가 트랜잭션 ID 랩어라운드 조건에 도달하기 시작할 때, 자동적으로 더욱 활성화되며 불필요한 정리를 건너뜁니다.
aggressive를 "공격적으로"라고 직역하기보다, 강하게 목적달성을 하기 위한 의미로 "더욱 활성화되며" 라고 번역해보았습니다

2022-05-06 21:40 UTC, HaeyoonJo commented on content/post/jamme-jellyfish-release-notes/index.md
> +- libpq는 다수의 쿼리와 결과를 보내고 받을 때, 대기시간이 긴 연결에서도 처리량을 높일 수 있는 파이프라인 모드를 지원합니다.
pipeline을 직역할지 고민하다가, 독자의 이해를 돕기위해 "파이프라인 모드"를 지원한다고 번역하였습니다.
또한, "다수의 쿼리와 결과를 보내고 받을 때"라고 풀어서 번역하였습니다

2022-05-07 13:54 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 베큠(VACUUM)은 데이터베이스가 트랜잭션 ID 랩어라운드 조건에 도달하기 시작할 때, 자동적으로 더욱 활성화되며 불필요한 정리를 건너뜁니다.
"적극적으로" 로 번역 하는 것도 좋을 것 같아요. 한번 고려 해 보시기 바랍니다 :)

2022-05-12 08:31 UTC, HaeyoonJo commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 베큠(VACUUM)은 데이터베이스가 트랜잭션 ID 랩어라운드 조건에 도달하기 시작할 때, 자동적으로 더욱 활성화되며 불필요한 정리를 건너뜁니다.
네, 번역 개선후 다시 PR 하겠습니다

2022-05-24 20:30 UTC, HaeyoonJo commented
@sukso96100 @minwook-shin @sigmadream @onting PostgreSQL 번역본에 대한 PR이 아직 남아있어서 태그드립니다.

2022-05-24 23:42 UTC, sukso96100 commented
> @sukso96100 @minwook-shin @sigmadream @onting PostgreSQL 번역본에 대한 PR이 아직 남아있어서 태그드립니다. 

아 검토 받을 준비 되신거면 draft 상태를 해제 해 주셔야... 곧 검토 하겠습니다

2022-05-25 05:01 UTC, sukso96100 commented
@HaeyoonJo 혹시 검토 받을 준비 되신 거라면 draft -> open 상태로 변경 해 주시겠어요?

2022-05-25 10:51 UTC, sukso96100 requested changes
커멘트를 참고 하셔서 수정된 번역을 제출 해 주세요.

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 저장 프로시저는 OUT 파라미터들을 통해 데이터를 반환할 수 있습니다.
```suggestion
- 이제 저장 프로시저에서 OUT 파라미터를 통해 데이터를 반환할 수 있습니다.
```

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 베큠(VACUUM)은 데이터베이스가 트랜잭션 ID 랩어라운드 조건에 도달하기 시작할 때, 자동적으로 주도해가면서 불필요한 정리를 건너뜁니다.
VACUM 이라는 기능이 더 적극적으로 작동한다는 의미인거 같은데요. 주도적은 "leading" 에 해당되서 "적극적으로" 가 맞는 번역 같습니다.

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 자동 AppConfig 검색
discovery 는 "탐색", "디스커버리" 로 번역하는것이 좀더 좋지 않나 싶습니다.

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 기능 인덱스
보통 functional 이라 하면 함수형 이라고 하는 것 같은데, Django 문서에서 functional index 가 기능 인덱스인지 함수형 인댁스인지 한번 찾아보시면 좋을 것 같습니다.

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 지원되는 모든 데이터베이스 백엔드에 대한 JSON 필드
`JSONField`는 Django 의 클래스 이름이네요. 고유명사 처리 하시면 되겠습니다.
https://docs.djangoproject.com/en/4.0/ref/models/fields/#jsonfield

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +이전 버전에서 업그레이드하는 사용자는 다음과 같이 이전 버전과의 비호환성을 인지하고 있어야합니다.
```suggestion
이전 버전에서 업그레이드하는 사용자는 다음과 같이 이전 버전과의 비호환성을 인지하고 있어야 합니다.

```

2022-05-25 10:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +추가적인 정보로, 이전 v2.2 LTS에서 Ubuntu 22.04의 v3.2 LTS로 업데이트 된 시점부터는 [3.2](https://docs.djangoproject.com/en/4.0/)의 Django 프로젝트 릴리즈 노트뿐 아니라, [3.1](https://docs.djangoproject.com/en/4.0/releases/3.1) 및 [3.0](
```suggestion
추가적인 정보로, 이전 v2.2 LTS에서 Ubuntu 22.04의 v3.2 LTS로 업데이트 된 시점부터는 [3.2](https://docs.djangoproject.com/en/4.0/)의 Django 프로젝트 릴리즈 노트뿐 아니라, [3.1](https://docs.djangoproject.com/en/4.0/releases/3.1) 및 [3.0](https://docs.djangoproject.com/en/4.0/releases/3.0)과 3.2.12까지 포함된 다양한 부가 릴리즈까지 포함된 내용을 확인하십시오.
```

2022-05-25 11:23 UTC, onting requested changes
대부분 자연스럽게 잘 표현하신 것 같습니다만 제가 볼 때 살짝 이상한 부분을 적어 봤습니다.
제가 아직 리뷰에 능숙하지 않아서 엉뚱한 지적을 했으면 양해 부탁드립니다.

2022-05-25 11:23 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +- libpq는 다수의 쿼리와 결과를 보내고 받을 때, 대기시간이 긴 연결에서도 처리량을 높일 수 있는 파이프라인 모드를 지원합니다.
제 생각에는 지연시간이 '긴 조건에서 속도 향상을 할 수 있도록 다수 쿼리를 파이프라이닝 할 수 있게 되었다'라는 문맥이 자연스러운 것 같습니다.

2022-05-25 11:23 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 지원되는 모든 데이터베이스 백엔드에 대한 JSON 필드
JSONField는 고유명사로 보이기 때문에 그대로 두는 것이 좋을 것 같습니다.

2022-05-25 11:23 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 그 외 다양한 주요 기능과 부가 기능에 대한 자세한 내용은 [릴리즈 노트](https://docs.djangoproject.com/en/4.0/releases/3.2/)를 참조하세요
하십시오체로 바꾸어 주세요

2022-05-25 11:23 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +변경 사항:
'다음에 대해 변경이 있었음'과 같은 느낌으로 바꾸면  어떨까요?

2022-05-25 11:23 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +이러한 추가 개선사항 및 버그수정에 대한 목록은 릴리즈 노트 [v14](https://www.postgresql.org/docs/14/release-14.html),
'이런 사항들과 버그 수정을 비롯한 장문의 추가 개선사항들은~~' 과 같은 형식으로 수정하는 것은 어떨까요?
원문의 의미가 조금 빠진 느낌이 듭니다.

2022-05-25 11:29 UTC, onting commented
이런 영빈님이 리뷰 올리신걸 못봤네요 중복되는 부분은 양해 부탁드립니다.

2022-05-25 12:18 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 지원되는 모든 데이터베이스 백엔드에 대한 JSON 필드
영빈님이 말씀하신 내용입니다.

2022-05-25 19:51 UTC, HaeyoonJo commented
우선, 종료시간에 거의 맞추어서 번역을 제출하게 되어 매우 죄송합니다.
평소 생활에서 한국어를 많이 사용할 수 없는 환경이라, 번역에서 다소 매끄럽지 않은 부분이 많았을 것 같습니다. 양해부탁드립니다. 

@sukso96100 , @onting 님께서 검토해주신 내용을 바탕으로 다시 업데이트하였으므로, 검토부탁드리겠습니다. 감사합니다

2022-05-26 03:35 UTC, sukso96100 requested changes
거의 다 된 것 같네요.

2022-05-26 03:35 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 베큠(VACUUM)은 데이터베이스가 트랜잭션 ID 랩어라운드 조건에 도달하기 시작할 때, 적극적으로 주도해가면서 불필요한 정리를 건너뜁니다.
```suggestion
- 베큠(VACUUM)은 데이터베이스가 트랜잭션 ID 랩어라운드 조건에 도달하기 시작할 때, 자동으로 더 적극적으로 작동하며 불필요한 정리를 건너뜁니다.
```

2022-05-26 08:42 UTC, onting approved these changes

2022-05-26 08:48 UTC, sukso96100 approved these changes
수고하셨습니다 :)

2022-05-26 08:48 UTC, merged