Squid advantage
ubuntu-kr/blog.ubuntu-kr.org pull request #41
Opened 2022-05-08 07:55 UTC by neeks76

검토 부탁드려요~~~

2022-05-08 18:02 UTC, sukso96100 requested changes
고칠 부분이 많습니다. 꼼꼼하게 확인 하셔서 수정된 번역을 제출 해 주세요.
저번처럼 Pull Request 새로 열지 마시고, 커밋 추가로 푸시 하시면 됩니다.

어떻게 번역할 지 모르겠는 부분은 요즘 구글 번역기나 파파고 번역 성능이 좋습니다. 완벽한 번역을 제공하진 않지만, 참고할 만한 번역을 제공하니 잘 활용하시기 바랍니다. 

또한 각 소프트웨어나 패키지별로 사용하는 고유한 용어가 있는 경우가 많으니, 필요한 경우 해당 소프트웨어의 문서도 참고해서 오역하는 일이 없도록 주의 하시기 바랍니다.

2022-05-09 01:41 UTC, sigmadream commented on content/post/jamme-jellyfish-release-notes/index.md
> +   * 사용자가 제공한 설정에 상세 오류 주석을 달기위한 '#cloud-config' 유효성 검사 스키마
'#cloud-config' 가 아니라 `#cloud-config` 로 적어주세요. 단어 강조는 single quote(')가 아니라 backtie(`) 입니다.

2022-05-11 11:21 UTC, sukso96100 requested changes
몇 가지만 조금 더 개선하면 될 것 같네요. 수고 많으셨습니다..

2022-05-11 11:21 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +* `squid` 패키지는 GnuTLS 라이브러리에 연결됩니다. OpenSSL을 사용하길 원하신다면, 새로운 `quid-openssl` 패키지를 설치 할 수 있습니다.
```suggestion
* `squid` 패키지는 GnuTLS 라이브러리에 연결됩니다. OpenSSL을 사용하길 원하신다면, 새로운 `squid-openssl` 패키지를 설치 할 수 있습니다.
```
`s`하나 빼먹으셨네요

2022-05-11 11:21 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +마지막 LTS 이후 도입된 주목할만한 기능 소개:
```suggestion
마지막 LTS 릴리즈 이후 도입된 주목할만한 기능:  
```

2022-05-11 11:21 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +   * LXD 소켓에 활성화된 임시 데이터를 읽고 재부팅 시에 설정 변경 사항을 적용하는 LXD datasource가 Jammy에 추가됨
```suggestion
   * LXD 소켓에서 동적 인스턴스 데이터를 읽어 재부팅 시에 구성 변경 사항을 적용하는 LXD datasource가 Jammy에 추가됨 
```

여러번 알려드렸지만, config, configuration은 "구성"으로 번역하시기 바랍니다.

2022-05-11 11:21 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +   * 오픈스택과 ConfigDrive 에는 [사용자 데이타에 의한 옵트인 핫플러그 네트워크 지원](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#install-hotplug) 추가됨
```suggestion
   * 오픈스택과 ConfigDrive용 [사용자 데이터에 의한 옵트인 핫플러그 네트워크 지원](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#install-hotplug)이 추가됨
```

2022-05-11 11:21 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +Jammy와 함께 Ubuntu-advantage-tools 버전 27.8 이 배포됨.
```suggestion
Jammy와 함께 Ubuntu-advantage-tools 버전 27.8 이 릴리즈됨.
```

2022-05-11 13:44 UTC, sigmadream approved these changes
번역에 기여해주셔서 감사드립니다. 좋은 경험 되셨으면 좋겠네요. 

@sukso96100 님이 리뷰 꼼꼼히 해주셔서 덕분에 저도 많이 배우고, 옵저버로 번역해주신거 확인했습니다. 

수고하셨습니다.

2022-05-11 13:49 UTC, sukso96100 requested changes

2022-05-11 13:49 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +   * LXD 소켓에서 동작 인스턴스 데이터를 읽어 재부팅 시에 구성 변경 사항을 적용하는 LXD datasource가 Jammy에 추가됨
```suggestion
   * LXD 소켓에서 동적 인스턴스 데이터를 읽어 재부팅 시에 구성 변경 사항을 적용하는 LXD datasource가 Jammy에 추가됨 

```

2022-05-11 13:50 UTC, sukso96100 approved these changes
고생 많으셨습니다 :) 이제 병합 하도록 하겠습니다.

2022-05-11 13:51 UTC, merged