플랫폼 부분의 s390x 부분 번역
ubuntu-kr/blog.ubuntu-kr.org pull request #49
Opened 2022-05-25 12:12 UTC by onting

Close #11 
s390x 부분의 번역입니다.
문장 구조가 까다로워서 번역이 매끄럽게 되지 않은 감이 있습니다.
개선 사항들을 제시해주시면 감사하겠습니다.

2022-06-03 14:04 UTC, sukso96100 requested changes
번역 하시느라 수고 많으셨습니다. 커멘트를 참고하셔서 개선 해 주세요.

2022-06-06 03:19 UTC, sukso96100 commented
@onting 수정 부탁드립니다~ 이 PR만 마무리 하면 번역 끝나서 배포가 가능할 것 같네요 :)

2022-06-07 10:25 UTC, onting commented on content/post/jamme-jellyfish-release-notes/index.md
> +    * SIMD 구현을 사용하게 되는 chacha20의 커널 자체 최적화 ([버그 1853152](https://bugs.launchpad.net/bugs/1853152))
저도 그 뜻으로 번역했는데 어색했나보네요.
수정했습니다.

2022-06-07 11:29 UTC, sukso96100 approved these changes
네 고생하셨습니다 :)

2022-06-07 11:31 UTC, merged