Ubuntu Server: MySQL 8.0 ~ Samba server 번역
ubuntu-kr/blog.ubuntu-kr.org pull request #51
Opened 2022-05-26 12:46 UTC by neeks76

이렇게 하면 되나요?

2022-05-26 14:03 UTC, neeks76 commented on content/post/jamme-jellyfish-release-notes/index.md
> +어떤 이유로든 변환 스크립트가 실패하면 패키지 설치 또는 업그레이드가 실패하고 이 문제를 해결해야 합니다. 이러한 상황이 발생하면, 부탁입니다.[Launchpad의 `nfs-utils`에 버그를 제출하십시오.]
gedit 에서 밑줄이 Ctrl+u 가 아니네요..ㅜㅜ;;
밑줄 긋는 방법좀 알려주셔요...??

2022-05-28 08:51 UTC, sukso96100 requested changes
커멘트를 확인 하셔서 조금 더 개선 해 주시기 바랍니다.

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- 데이타 타입 업데이트
```suggestion
- 데이터 타입 업데이트
```

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +- CPU_TIME 기재 메트릭
데이터베이스에서 Statement 를 "기재"라고 번역 할까요? _DB 쿼리**문**_ 의 맥락에서, **문**으로 옮기는 것이 맞는 것 같은데요, `CPU_TIME` 이 무엇인지 찾아 보시고 수정 해 주시면 좋을 것 같습니다.
```suggestion
- CPU_TIME 문 메트릭
```

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +업그레이드 중에 `/etc/default/nfs-*` 파일이 변경되었음을 패키지가 감지하면 변환 스크립트가 실행됩니다. 이 스크립트는 `/usr/share/sshare-common/nfsconvert.py`이며 `/etc/sshare-*`에서 옵션을 읽고 `/etc/sshare.conf.d/local.conf`를 생성합니다. 여기서 `/etc/sshare
which overrides the defaults in `/etc/nfs.conf`.
에 대한 번역이 없네요

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +어떤 이유로든 변환 스크립트가 실패하면 패키지 설치 또는 업그레이드가 실패하고 이 문제를 해결해야 합니다. 이러한 상황이 발생하면, 부탁합니다.[Launchpad의 `nfs-utils`에 버그를 제출하십시오.]
Please 가 붙은 문장은 "부탁합니다" 로도 옮기실 수 있지만, 꼭 ~~ 해 주세요 등으로도 옮기실 수 있습니다.

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +Samba는 4.15.5로 업데이트되었는데, 이것은 몇 가지 주목할 만한 변화를 가져왔습니다. 다음을 참고하십시오 [upstream 릴리스 정보에 대한 상세](https://www.samba.org/samba/history/samba-4.15.0.html), 다음은 주요 내용입니다.:
```suggestion
Samba는 4.15.5로 업데이트되었는데, 이것은 몇 가지 주목할 만한 변화를 가져왔습니다. [자세한 사항은 upstream 릴리스 노트를](https://www.samba.org/samba/history/samba-4.15.0.html) 확인 하십시오, 다음은 주요 내용입니다.:
```

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +* SMB 버전 SMB2_22, SMB2_24 및 SMB3_10은 더 이상 인식되지 않습니다. SMB2_22 및 SMB2_24는 SMB3_00으로, SMB3_10은 SMB3_11로 대체해야 합니다.
The development SMB versions 에서 development 를 빼고 번역 하셨네요.

2022-05-28 08:51 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +* 서버 다중 채널 지원은 더 이상 실험적이지 않음
이 맥락에서는 "실험적 기능"으로 조금 의역해도 좋을 것 같습니다.

2022-06-01 12:21 UTC, sukso96100 commented
@neeks76 추가 수정 작업 중이신지요?

2022-06-01 12:26 UTC, neeks76 commented
@sukso96100 네에..

2022-06-01 13:20 UTC, sukso96100 requested changes

2022-06-01 13:21 UTC, sukso96100 approved these changes
수고 많으셨습니다. 병합 하도록 하겠습니다 :)

2022-06-01 13:24 UTC, sukso96100 requested changes

2022-06-01 13:24 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> +* 많은 /etc/syslog/syslog.conf 매개 변수가 변경되었으며 일부는 제거되었습니다. 자세한 내용은 다음을 참고하십시오. [Upstream 릴리스 정보](https://www.samba.org/samba/history/samba-4.15.0.html)
```suggestion
* 많은 `/etc/syslog/syslog.conf` 매개 변수가 변경되었으며 일부는 제거되었습니다. [업스트림 릴리스 노트](https://www.samba.org/samba/history/samba-4.15.0.html)를 확인 해 주십시오.
```

2022-06-01 13:25 UTC, sukso96100 approved these changes

2022-06-01 13:25 UTC, merged