Ubuntu Frame 관련 새 포스팅
ubuntu-kr/blog.ubuntu-kr.org pull request #55
Opened 2023-02-08 05:14 UTC by onting

작년 우부콘 아시아에서 제가 진행했던 워크숍 내용을 정리하는 포스팅입니다.

2023-02-08 05:17 UTC, onting commented
일단 PR을 열어 놨으니 천천히 읽어보시고 개선 사항들이 있으면 알려주시기 바랍니다.

2023-02-09 04:01 UTC, sukso96100 commented on content/post/ubuntuframe-recap/index.md
> +
이 부분은 아직 작성 중인 거죠? 아니면 별도 포스팅으로 작성 될까요?

2023-02-09 06:32 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +
작성 중인 부분입니다.

2023-02-09 06:33 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +
실제 리눅스에서 돌려야 하는 것들이 좀 있어서 시간이 걸리고 있네요

2023-02-09 06:35 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +
윈도우에서 하기엔 multipass, wsl, virtualbox 전부 서로 조금씩 안되는 부분이 있네요 😅

2023-02-21 14:14 UTC, sukso96100 commented
글이 조금 긴 것 같은데, Ubuntu Frame 소개와 실습 내용으로 포스팅을 쪼개는 것은 어떨까요?

2023-02-21 23:30 UTC, onting commented
역시 그럴까요?
분량은 알아서 끊어 읽는다는 생각이었지만 얘길 들어보니 2개로 쪼개는 것도 괜찮을 것 같습니다.
오늘 중 올릴게요.

2023-02-22 02:03 UTC, onting commented
일단 나눠 봤습니다. 개선 점 있으면 알려주세요

2023-02-25 10:39 UTC, sukso96100 requested changes

2023-02-25 10:39 UTC, sukso96100 commented
@sigmadream 님도 혹시 가능하시면 한번 리뷰 부탁드려도 될까요?

2023-02-25 15:30 UTC, sigmadream reviewed
몇가지 리뷰 입니다.

2023-02-25 15:30 UTC, sigmadream commented on content/post/ubuntuframe-recap/index.md
> +[Ubuntu Frame의 공식 설명](https://github.com/MirServer/ubuntu-frame#description)을 보면 Ubuntu Frame은 "다양한 임베디드 그래픽 디스플레이 구현을 위한 기반이며, 단순한 Full-screen Shell을 제공해서 키오스크, 안내판 등에 활용될 수 있다."라고 설명되고 있습니다. 즉 아래 그
다른 사이트 인용의 경우 마크다운의 `>`를 사용해서 원문을 함께 제시해주시면 링크를 안 눌러도 되서 읽는데 훨씬 효율적입니다. 예를 들어, 아래와 같은 형태로 구성하시면 링크 안 타고 가도 내용을 이해하는데 충분하리라 생각됩니다.

...Ubuntu Frame에 대한 소개는 아래와 같고, 핵심적인 내용은 "다양한 임베디드 그래픽 디스플레이 구현을 위한 기반이며, 단순한 Full-screen Shell을 제공해서 키오스크, 안내판 등에 활용될 수 있다."라고 설명되어 있습니다.
> The foundation for many embedded graphical display implementations. ubuntu-frame is a simple fullscreen shell (based on Wayland) used for kiosks, industrial displays, digital signage, smart mirrors, etc.

2023-02-25 15:30 UTC, sigmadream commented on content/post/ubuntuframe-recap/index.md
> +임베디드 시스템에서는 다양한 작업을 해야하는 PC와 달리 정해진 작업들을 안정적으로 수행하는 것이 중요합니다. 반면, 컴퓨터 시스템에서 더 많은 기능들은 더 많은 결함 발생 가능성을 의미하기 때문에 안정성과 하드웨어 비용을 위해서 리눅스 이미지 맞춤 제작이 임베디드에서는 화두되고 있습니다. 그러나 리눅스 맞춤 제작은 실제로는 굉장히 어려운 문제입니다. 리
문단을 나누실 생각이면 빈 줄을 활용해서 완전히 나눠주시고, 문단을 나누실 의도가 아니시면 한 줄에 이어쓰시는게 좋습니다. 위에 40번 줄에 "그런데"는 문단이 나뉘고, 나머지는 한 문단으로 구성되는 구조로 보여지는거라 문단을 나누실 꺼면 "빈줄" 활용하시면 좋을 것 같네요.

2023-02-25 15:30 UTC, sigmadream commented on content/post/ubuntuframe-recap/index.md
> +분량 조절을 위해서 이 글에선 Ubuntu Frame에 대한 개념 설명을 끝으로 마치고 다음 글에서 실습을 해보겠습니다.
가능하시면 "다음 글"에 링크 걸어주시면 읽는데 불편함이 없을 듯 하네요.

2023-02-25 15:30 UTC, sigmadream commented on content/post/ubuntuframe-recap/index.md
> +3. [데스크톱 환경에서 실습하기](#desktop-환경에서-실습하기)
해당 링크 작동하지 않으니 수정해주세요.

2023-02-25 15:30 UTC, sigmadream commented on content/post/ubuntuframe-recap-exercise/index.md
> +다시 돌아와, 우리가 바꿀 부분은 ```parts``` 속성의 ```electron-helloworld``` 부분입니다. ```parts```는 패키지를 구성하는 요소들을 의미하는데 앱, 라이브러리, 정적 에셋 등 다양한 요소들이 part로 기술 될 수 있고 part를 위한 빌드, 실행 환경, 의존성 등을 포함할 수 있습니다.
빈 줄을 활용해서 문단을 나눠주시면 좋을 것 같네요. 그리고 인용 코드가 "다시 돌아와" 위에 붙는게 가독성에 더 좋을 듯 합니다.

2023-02-25 15:30 UTC, sigmadream commented on content/post/ubuntuframe-recap-exercise/index.md
> +$ snap install --dangerous *.snap
가능하시면 설치 후 화면도 보여주시면 좋을 듯 합니다.

2023-02-27 04:54 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +[Ubuntu Frame의 공식 설명](https://github.com/MirServer/ubuntu-frame#description)을 보면 Ubuntu Frame은 "다양한 임베디드 그래픽 디스플레이 구현을 위한 기반이며, 단순한 Full-screen Shell을 제공해서 키오스크, 안내판 등에 활용될 수 있다."라고 설명되고 있습니다. 즉 아래 그
네 적용해보겠습니다.

2023-02-27 05:23 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +3. [데스크톱 환경에서 실습하기](#desktop-환경에서-실습하기)
반영했습니다

2023-02-27 05:23 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +분량 조절을 위해서 이 글에선 Ubuntu Frame에 대한 개념 설명을 끝으로 마치고 다음 글에서 실습을 해보겠습니다.
반영했습니다

2023-02-27 05:25 UTC, onting commented on content/post/ubuntuframe-recap-exercise/index.md
> +$ snap install --dangerous *.snap
이건 회장에서 시연했을 때는 잘 됐는데 다시 하려고 하니까 잘 안돼서 안 넣었는데 딱 걸렸네요;
일단 다시 시도해보겠습니다.

2023-02-27 05:31 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +임베디드 시스템에서는 다양한 작업을 해야하는 PC와 달리 정해진 작업들을 안정적으로 수행하는 것이 중요합니다. 반면, 컴퓨터 시스템에서 더 많은 기능들은 더 많은 결함 발생 가능성을 의미하기 때문에 안정성과 하드웨어 비용을 위해서 리눅스 이미지 맞춤 제작이 임베디드에서는 화두되고 있습니다. 그러나 리눅스 맞춤 제작은 실제로는 굉장히 어려운 문제입니다. 리
반영했습니다

2023-02-27 05:32 UTC, onting commented on content/post/ubuntuframe-recap/index.md
> +[Ubuntu Frame의 공식 설명](https://github.com/MirServer/ubuntu-frame#description)을 보면 Ubuntu Frame은 "다양한 임베디드 그래픽 디스플레이 구현을 위한 기반이며, 단순한 Full-screen Shell을 제공해서 키오스크, 안내판 등에 활용될 수 있다."라고 설명되고 있습니다. 즉 아래 그
반영했습니다

2023-02-27 06:10 UTC, onting commented on content/post/ubuntuframe-recap-exercise/index.md
> +$ snap install --dangerous *.snap
단순히 메모리가 적어서 로드가 잘 안됐나 봅니다. 반영해서 올리겠습니다.

2023-02-27 08:27 UTC, onting commented on content/post/ubuntuframe-recap-exercise/index.md
> +다시 돌아와, 우리가 바꿀 부분은 ```parts``` 속성의 ```electron-helloworld``` 부분입니다. ```parts```는 패키지를 구성하는 요소들을 의미하는데 앱, 라이브러리, 정적 에셋 등 다양한 요소들이 part로 기술 될 수 있고 part를 위한 빌드, 실행 환경, 의존성 등을 포함할 수 있습니다.
반영했습니다

2023-02-28 10:04 UTC, sukso96100 approved these changes
이정도면 충분한 것 같습니다. 수고하셨습니다 :)

2023-02-28 12:07 UTC, merged

2023-03-01 04:37 UTC, onting commented
시간 내주어 리뷰해주셔서 고맙습니다, @sukso96100 님, @sigmadream 님. 항상 도와주셔서 감사합니다.